"""
Modal Dialogs and Text Input Popups for Shallot-CUI Bot.
"""

import logging
import discord
from core_helpers import send_error_fallback

logger = logging.getLogger("DiscordBot.Views.Modals")


class CustomSrefModal(discord.ui.Modal, title="Change Style Reference (--sref)"):
    sref_input = discord.ui.TextInput(
        label="Enter --sref code, style name, or image URL",
        placeholder="e.g. 772382, --sref 492104, or https://...",
        required=True,
        max_length=200
    )

    def __init__(self, generation_id: str, index: int, on_submit_callback=None):
        super().__init__()
        self.generation_id = generation_id
        self.index = index
        self.on_submit_callback = on_submit_callback

    async def on_submit(self, interaction: discord.Interaction):
        try:
            val = self.sref_input.value.strip()
            if val and self.on_submit_callback:
                await self.on_submit_callback(interaction, self.generation_id, self.index, val)
        except Exception as e:
            logger.error(f"Error in CustomSrefModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to apply style reference: {e}")


class SavedSrefSelectView(discord.ui.View):
    def __init__(self, generation_id: str, index: int, favorites: list[dict], select_callback=None):
        super().__init__(timeout=60)
        self.generation_id = generation_id
        self.index = index
        self.callback_fn = select_callback

        options = []
        for fav in favorites[:25]:
            code = fav.get("style_code")
            name = fav.get("style_name", f"Style {code}")
            options.append(discord.SelectOption(
                label=name[:100],
                value=str(code),
                description=f"--sref {code}"
            ))

        select = discord.ui.Select(
            placeholder="⭐ Choose a saved style from /my_prompts...",
            min_values=1,
            max_values=1,
            options=options
        )
        select.callback = self.on_select
        self.add_item(select)

    async def on_select(self, interaction: discord.Interaction):
        selected_code = interaction.data["values"][0]
        if self.callback_fn:
            await self.callback_fn(interaction, self.generation_id, self.index, selected_code)


class RemixModal(discord.ui.Modal, title="✏️ Remix / Tweak Prompt"):
    prompt_input = discord.ui.TextInput(
        label="Edit Prompt",
        style=discord.TextStyle.paragraph,
        required=True,
        max_length=2000
    )
    seed_input = discord.ui.TextInput(
        label="Seed (leave blank for random)",
        required=False,
        max_length=20
    )

    def __init__(self, generation_id: str, initial_prompt: str = "", initial_seed: int = None, on_submit_callback=None):
        super().__init__()
        self.generation_id = generation_id
        self.on_submit_callback = on_submit_callback
        self.prompt_input.default = initial_prompt
        if initial_seed is not None:
            self.seed_input.default = str(initial_seed)

    async def on_submit(self, interaction: discord.Interaction):
        try:
            p = self.prompt_input.value.strip()
            s = self.seed_input.value.strip()
            seed_val = int(s) if s.isdigit() else None
            if self.on_submit_callback:
                await self.on_submit_callback(interaction, self.generation_id, p, seed_val)
        except Exception as e:
            logger.error(f"Error in RemixModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to submit remix: {e}")


class EditBlendPromptModal(discord.ui.Modal, title="✏️ Edit & Refine Blend Prompts"):
    def __init__(self, generation_id: str, current_caption: str, current_detailed: str, current_extra: str = "", on_submit_callback=None):
        super().__init__()
        self.generation_id = generation_id
        self.on_submit_callback = on_submit_callback

        self.caption_input = discord.ui.TextInput(
            label="Caption (Short / Tags)",
            style=discord.TextStyle.paragraph,
            default=current_caption[:400] if current_caption else "",
            max_length=1000,
            required=False,
            placeholder="e.g. 1girl, solo, palshallot, adventurer outfit, looking at viewer"
        )
        self.add_item(self.caption_input)

        self.detailed_input = discord.ui.TextInput(
            label="Detailed Vision Description",
            style=discord.TextStyle.paragraph,
            default=current_detailed[:1500] if current_detailed else "",
            max_length=2000,
            required=False,
            placeholder="Edit or expand the scene description generated by Florence-2"
        )
        self.add_item(self.detailed_input)

        self.extra_input = discord.ui.TextInput(
            label="✨ Extra Details / Add-ons (Optional)",
            style=discord.TextStyle.short,
            default=current_extra[:200] if current_extra else "",
            max_length=400,
            required=False,
            placeholder="e.g. glowing magic aura, sunset rim light, cinematic lens flare"
        )
        self.add_item(self.extra_input)

    async def on_submit(self, interaction: discord.Interaction):
        try:
            if self.on_submit_callback:
                await self.on_submit_callback(
                    interaction,
                    self.generation_id,
                    self.caption_input.value.strip(),
                    self.detailed_input.value.strip(),
                    self.extra_input.value.strip()
                )
        except Exception as e:
            logger.error(f"Error in EditBlendPromptModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to update blend prompt: {e}")


class EditBlendKreaModal(discord.ui.Modal):
    def __init__(self, generation_id: str, current_prompt: str = "", on_submit_callback=None):
        super().__init__(title="✏️ Edit Generation Prompt")
        self.generation_id = generation_id
        self.on_submit_callback = on_submit_callback

        self.prompt_input = discord.ui.TextInput(
            label="Generation Prompt",
            style=discord.TextStyle.paragraph,
            default=current_prompt[:2000] if current_prompt else "",
            placeholder="Edit, add prefixes, or rewrite the generation prompt for Krea 2...",
            required=True,
            max_length=2000
        )
        self.add_item(self.prompt_input)

    async def on_submit(self, interaction: discord.Interaction):
        try:
            val = self.prompt_input.value.strip()
            if self.on_submit_callback:
                await self.on_submit_callback(interaction, self.generation_id, val)
        except Exception as e:
            logger.error(f"Error in EditBlendKreaModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to update Krea 2 prompt: {e}")


class StudyImagineModal(discord.ui.Modal, title="🎨 Imagine with Extracted Prompt"):
    prompt_input = discord.ui.TextInput(
        label="Prompt",
        style=discord.TextStyle.paragraph,
        placeholder="Enter or edit your prompt...",
        required=True,
        max_length=4000
    )
    flags_input = discord.ui.TextInput(
        label="Optional Flags (--ar, --sr, --sref, etc.)",
        style=discord.TextStyle.short,
        placeholder="e.g. --ar 16:9 --sr.60 --sref 772382",
        required=False,
        max_length=500
    )

    def __init__(self, initial_prompt: str, on_submit_callback=None):
        super().__init__()
        self.prompt_input.default = initial_prompt[:4000]
        self.on_submit_callback = on_submit_callback

    async def on_submit(self, interaction: discord.Interaction):
        try:
            full_prompt = self.prompt_input.value.strip()
            flags = self.flags_input.value.strip()
            if flags:
                full_prompt = f"{full_prompt} {flags}"
            if self.on_submit_callback:
                await self.on_submit_callback(interaction, full_prompt)
        except Exception as e:
            logger.error(f"Error in StudyImagineModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to queue generation: {e}")


class EditStyleModal(discord.ui.Modal, title="✏️ Edit Style Reference"):
    def __init__(self, user_id: int, style: dict, on_save_callback=None):
        super().__init__()
        self.user_id = user_id
        self.style_code = style["style_code"]
        self.on_save_callback = on_save_callback

        self.name_input = discord.ui.TextInput(
            label="Style Name",
            placeholder="e.g. Gothic Watercolor Wash",
            default=style.get("style_name", "")[:100],
            required=True,
            max_length=100
        )
        self.prompt_input = discord.ui.TextInput(
            label="Style Prompt",
            style=discord.TextStyle.paragraph,
            placeholder="Enter style prompt description...",
            default=style.get("style_prompt", "")[:2000],
            required=True,
            max_length=2000
        )
        self.add_item(self.name_input)
        self.add_item(self.prompt_input)

    async def on_submit(self, interaction: discord.Interaction):
        try:
            import db
            new_name = self.name_input.value.strip()
            new_prompt = self.prompt_input.value.strip()
            
            updated = db.update_favorite_style(self.user_id, self.style_code, new_name, new_prompt)
            if updated:
                if self.on_save_callback:
                    await self.on_save_callback(interaction, self.style_code, new_name, new_prompt)
                else:
                    await interaction.response.send_message(f"✅ Updated style `{new_name}` (Code: `{self.style_code}`).", ephemeral=True)
            else:
                await interaction.response.send_message("❌ Failed to update style.", ephemeral=True)
        except Exception as e:
            logger.error(f"Error in EditStyleModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to edit style: {e}")


class EditPromptModal(discord.ui.Modal, title="✏️ Edit Saved Prompt"):
    def __init__(self, user_id: int, prompt_data: dict, on_save_callback=None):
        super().__init__()
        self.user_id = user_id
        self.prompt_id = prompt_data["id"]
        self.on_save_callback = on_save_callback

        self.name_input = discord.ui.TextInput(
            label="Prompt Label / Nickname",
            placeholder="e.g. Semi-realism Girl",
            default=prompt_data.get("prompt_name", "")[:100],
            required=True,
            max_length=100
        )
        self.prompt_input = discord.ui.TextInput(
            label="Full Prompt Text",
            style=discord.TextStyle.paragraph,
            placeholder="Enter prompt text...",
            default=prompt_data.get("prompt_text", "")[:4000],
            required=True,
            max_length=4000
        )
        self.add_item(self.name_input)
        self.add_item(self.prompt_input)

    async def on_submit(self, interaction: discord.Interaction):
        try:
            import db
            new_name = self.name_input.value.strip()
            new_text = self.prompt_input.value.strip()
            
            updated = db.update_favorite_prompt(self.user_id, self.prompt_id, new_name, new_text)
            if updated:
                if self.on_save_callback:
                    await self.on_save_callback(interaction, self.prompt_id, new_name, new_text)
                else:
                    await interaction.response.send_message(f"✅ Updated prompt **\"{new_name}\"** (ID: `{self.prompt_id}`).", ephemeral=True)
            else:
                await interaction.response.send_message("❌ Failed to update prompt.", ephemeral=True)
        except Exception as e:
            logger.error(f"Error in EditPromptModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to edit prompt: {e}")


class EditAdoptPromptModal(discord.ui.Modal, title="✏️ Edit Adopted Prompt"):
    prompt_input = discord.ui.TextInput(
        label="Prompt Text",
        style=discord.TextStyle.paragraph,
        placeholder="Edit your prompt...",
        required=True,
        max_length=4000
    )

    def __init__(self, adopt_id: str, current_prompt: str, on_submit_callback=None):
        super().__init__()
        self.adopt_id = adopt_id
        self.prompt_input.default = current_prompt[:4000]
        self.on_submit_callback = on_submit_callback

    async def on_submit(self, interaction: discord.Interaction):
        try:
            new_prompt = self.prompt_input.value.strip()
            if self.on_submit_callback:
                await self.on_submit_callback(interaction, self.adopt_id, new_prompt)
        except Exception as e:
            logger.error(f"Error in EditAdoptPromptModal submit: {e}")
            await send_error_fallback(interaction, f"Failed to edit adopted prompt: {e}")
