"""
Parsers Package for Shallot-CUI Bot.
Provides prompt parsing, aspect ratio calculations, style generation, and ComfyUI workflow AST manipulations.
Re-exports all public APIs for 100% backward compatibility.
"""

from parsers.dimensions import (
    RE_ASPECT_RATIO,
    BERTFLOW_ASPECT_RATIOS,
    parse_aspect_ratio,
    calculate_wan_dimensions,
    resolve_bertflow_dimensions,
)

from parsers.styles import (
    SREF_MEDIUMS,
    SREF_STYLES,
    SREF_LIGHTING,
    SREF_PALETTES,
    SREF_TEXTURES,
    MAGIC_ENHANCEMENTS,
    RE_RAW,
    RE_STYLIZE,
    RE_SW,
    RE_SREF,
    parse_stylize,
    generate_dynamic_style,
    parse_sref,
)

from parsers.prompts import (
    RE_SEED,
    RE_POWERHOUSE,
    RE_FREEU,
    RE_CW,
    RE_CREF,
    RE_WHITESPACE,
    RE_WILDCARD_BLOCKS,
    RE_FLORENCE_BOILERPLATE,
    RE_PROSE_FILLER,
    RE_AN_OVERALL,
    RE_OVERALL,
    LOCKED_STYLE_PRESETS,
    truncate_prompt,
    find_common_prefix,
    find_common_suffix,
    clean_quadrant_prompts,
    deduplicate_intro_quality_tags,
    parse_seed,
    clean_midjourney_flags,
    parse_cref,
    expand_dynamic_prompt,
    parse_magic_prompt,
    parse_smart_prompt,
    parse_powerhouse_prompt,
    parse_freeu_prompt,
    apply_smart_magic_and_sref,
    apply_magic_enhancement,
    _clean_extracted_prompt,
    _is_negative_only,
    _parse_a1111_parameters,
    _resolve_comfy_node_text,
    _parse_comfy_api_prompt,
    _parse_comfy_workflow,
    _parse_comment_or_description,
    extract_positive_prompt,
    build_scapes_prompt,
    parse_video_motion_flags,
    sanitize_describe_text,
    format_sdxl_prompt,
    format_flux_prompt,
    format_krea2_prompt,
    fuse_krea2_blend_prompt,
)

from parsers.workflows import (
    _WORKFLOW_CACHE,
    RE_LORA_TAG,
    RE_SEMI_REALISM,
    RE_OGARLA,
    load_workflow_template,
    parse_loras,
    validate_workflow_loras,
    apply_loras_to_workflow,
    apply_face_detailer_to_workflow,
    apply_ipadapter_to_workflow,
    get_bertflow_unet_model,
    prepare_bertflow_workflow,
)

__all__ = [
    # dimensions
    "RE_ASPECT_RATIO",
    "BERTFLOW_ASPECT_RATIOS",
    "parse_aspect_ratio",
    "calculate_wan_dimensions",
    "resolve_bertflow_dimensions",
    # styles
    "SREF_MEDIUMS",
    "SREF_STYLES",
    "SREF_LIGHTING",
    "SREF_PALETTES",
    "SREF_TEXTURES",
    "MAGIC_ENHANCEMENTS",
    "RE_RAW",
    "RE_STYLIZE",
    "RE_SW",
    "RE_SREF",
    "parse_stylize",
    "generate_dynamic_style",
    "parse_sref",
    # prompts
    "RE_SEED",
    "RE_POWERHOUSE",
    "RE_FREEU",
    "RE_CW",
    "RE_CREF",
    "RE_WHITESPACE",
    "RE_WILDCARD_BLOCKS",
    "RE_FLORENCE_BOILERPLATE",
    "RE_PROSE_FILLER",
    "RE_AN_OVERALL",
    "RE_OVERALL",
    "LOCKED_STYLE_PRESETS",
    "truncate_prompt",
    "find_common_prefix",
    "find_common_suffix",
    "clean_quadrant_prompts",
    "deduplicate_intro_quality_tags",
    "parse_seed",
    "clean_midjourney_flags",
    "parse_cref",
    "expand_dynamic_prompt",
    "parse_magic_prompt",
    "parse_smart_prompt",
    "parse_powerhouse_prompt",
    "parse_freeu_prompt",
    "apply_smart_magic_and_sref",
    "apply_magic_enhancement",
    "_clean_extracted_prompt",
    "_is_negative_only",
    "_parse_a1111_parameters",
    "_resolve_comfy_node_text",
    "_parse_comfy_api_prompt",
    "_parse_comfy_workflow",
    "_parse_comment_or_description",
    "extract_positive_prompt",
    "build_scapes_prompt",
    "parse_video_motion_flags",
    "sanitize_describe_text",
    "format_sdxl_prompt",
    "format_flux_prompt",
    "format_krea2_prompt",
    "fuse_krea2_blend_prompt",
    # workflows
    "_WORKFLOW_CACHE",
    "RE_LORA_TAG",
    "RE_SEMI_REALISM",
    "RE_OGARLA",
    "load_workflow_template",
    "parse_loras",
    "validate_workflow_loras",
    "apply_loras_to_workflow",
    "apply_face_detailer_to_workflow",
    "apply_ipadapter_to_workflow",
    "get_bertflow_unet_model",
    "prepare_bertflow_workflow",
]
